name: CI and Deploy Pipeline

on:
  push:
    branches:
      - TestedBranch
  pull_request:
    branches:
      - TestedBranch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Archive Artifact
        uses: actions/upload-artifact@v3
        with:
          name: java-artifact
          path: target/*.war

  trigger-jenkins-job:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: java-artifact
          path: ./artifacts

      - name: Get Jenkins Crumb
        id: get-crumb
        run: |
          CRUMB=$(curl -u "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}" -s "${{ secrets.JENKINS_URL }}/crumbIssuer/api/json" | jq -r '.crumb')
          echo "::set-output name=crumb::$CRUMB"

      - name: Upload WAR to Jenkins and Trigger Job
        run: |
          curl -X POST "${{ secrets.JENKINS_URL }}/job/${{ secrets.JENKINS_JOB_NAME }}/buildWithParameters?token=${{ secrets.JENKINS_AUTH_TOKEN }}" \
            -F "file=@./artifacts/java-artifact.war" \
            -H "Jenkins-Crumb: ${{ steps.get-crumb.outputs.crumb }}" \
            --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}"
